#!/bin/bash
for SF_ELO in 1500 1600 1700 1800; do
    cutechess-cli \
      -engine cmd=./target/release/chess-badfish name=BadFish proto=uci \
      -engine cmd=stockfish name=SF$SF_ELO proto=uci \
        option.UCI_LimitStrength=true option.UCI_Elo=$SF_ELO option.Threads=1 \
      -each tc=10+0.1 \
      -games 2 -rounds 100 \
      -repeat -concurrency 6 \
      -resign movecount=5 score=600 \
      -draw movenumber=40 movecount=8 score=10 \
      -openings file=openings.pgn order=random \
      -pgnout vs_sf_$SF_ELO.pgn
done