#!/bin/bash
cargo build --release

cutechess-cli \
  -engine cmd=./target/release/chess-badfish name=New proto=uci \
  -engine cmd=./target/release/chess-badfish name=New proto=uci \
  -each tc=10+0.1 \
  -games 200 \
  -rounds 500 \
  -repeat \
  -concurrency 6 \
  -resign movecount=5 score=600 \
  -draw movenumber=40 movecount=8 score=10 \
  -openings file=openings.pgn order=random \
  -sprt elo0=0 elo1=5 alpha=0.05 beta=0.05 \
  -pgnout 100kgames.pgn

