#!/bin/bash
cutechess-cli \
  -engine cmd=./target/release/chess-badfish name=Newest proto=uci \
  -engine cmd=./saved-brains/v7 name=BadFish7 proto=uci \
  -each tc=10+0.1 \
  -games 2 \
  -rounds 5000 \
  -repeat \
  -concurrency 5 \
  -resign movecount=5 score=600 \
  -draw movenumber=40 movecount=8 score=10 \
  -openings file=openings.pgn order=random \
  -sprt elo0=0 elo1=10 alpha=0.05 beta=0.05
